### ISSUE TITLE
Hang around input option

### ISSUE THREAD

**Issue by gbraad** [gbraad-actions/codium-server-action#4]
```yaml
name: My Composite Action
inputs:
  hangaround:
    description: 'Run the hangaround step'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Always runs
      run: echo "This step always runs"
    - name: Only runs if hangaround is set
      if: ${{ inputs.hangaround == 'true' }}
      run: echo "Hangaround is enabled!"
```
